refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  file:
    kind: file
    path: "log/backtest.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S%.6f)} {M}] {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - file
