sandbox = true
access_token = ""
sandbox_token = ""
account_id = ""
mongo_url = "mongodb://localhost:27017/"

[[strategies]]
name = "mean-reversion"
symbols = ["SPY", "AAPL"]
capital = [10000, 10000]

# [[strategies]]
# name = "pairs"
# symbols = []
