refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  file:
    kind: rolling_file
    path: "log/trading.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S%.6f)} {M}] {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: time
        interval: 1 day
      roller:
        kind: fixed_window
        base: 1
        count: 20
        pattern: "log/trading.{}.log"

root:
  level: info
  appenders:
    - stdout
    - file
